/*
  نصوص المتجر بثلاث لغات (ar / en / tr). المفاتيح تُربَط بـ data-i في الصفحة.
  إعدادات المتجر (رقم واتساب والعملة) في CONFIG: غيّر الرقم هنا فقط ليصل الطلب إلى صاحب المتجر.
*/
export const CONFIG = {
  wa: '905537410520',     // رقم واتساب المتجر (دولي بلا + ولا أصفار)
  currency: '₺',
  brand: 'MOHAMMED'
};

export const T = {
  ar: {
    title: 'محمد · ساعات وفضيات بأحجار كريمة',
    brandSub: 'ساعات · فضة · أحجار كريمة',
    nav_collection: 'المجموعة', nav_atelier: 'الأتيليه', nav_story: 'الحرفة', nav_order: 'الطلب',
    sound_on: 'تشغيل الصوت', sound_off: 'كتم الصوت', bag: 'الحقيبة', bag_open: 'افتح الحقيبة', lang: 'اللغة',
    loader: 'يُجهَّز المعرض',
    scroll: 'مرّر للأسفل',
    c0_k: 'ساعات · فضة · أحجار كريمة', c0_t: 'الوقت يليق بالفضة', c0_p: 'ساعات وفضيات بأحجار كريمة، بتفاصيل لا تُرى إلا عن قرب. هذه الساعة تدقّ الآن بتوقيتك.',
    c1_k: 'تشريح ساعة', c1_t: 'ما تحت الميناء', c1_p: 'زجاج، ميناء، حركة، علبة. أربع طبقات تعمل معاً، وفي القلب ثلاث جواهر ياقوت.',
    a_crystal: 'الزجاج', a_dial: 'الميناء', a_movement: 'الحركة', a_case: 'علبة الفضة',
    c2_k: 'فضة بأحجار كريمة', c2_t: 'حجر واحد يغيّر القطعة', c2_p: 'ياقوت وزمرد وفيروز وعقيق، يُختار كل حجر ويُرصَّع في فضة عيار 925.',
    c3_k: 'مسابح وبلاكات', c3_t: 'مسبحة، وبلاكة باسمك', c3_p: '33 حبّة من الكهرمان أو الأونيكس أو الفضة، وبلاكة تُنقش بالاسم الذي تحب.',
    c4_k: 'المجموعة', c4_t: 'كل هذا في مكان واحد', c4_p: 'ست ساعات، سبعة خواتم، بلاكات، طواق وسلاسل، ومسابح. اختر ما يشبهك.', c4_cta: 'تصفّح المجموعة',
    trust1_t: 'فضة عيار 925', trust1_p: 'فضة استرلينغ خالصة',
    trust2_t: 'نقش باسمك', trust2_p: 'على البلاكات والخواتم',
    trust3_t: 'تغليف هدية', trust3_p: 'علبة مخمل مع كل طلب',
    trust4_t: 'الطلب بواتساب', trust4_p: 'سلة تُرسل إليك مباشرة',
    col_k: 'المجموعة', col_t: 'اختر قطعتك', col_p: 'ساعات وخواتم وبلاكات وطواق ومسابح، كلها بالليرة التركية.',
    f_all: 'الكل', f_watch: 'ساعات', f_ring: 'خواتم', f_pendant: 'بلاكات', f_necklace: 'طواق وسلاسل', f_tasbih: 'مسابح',
    sort: 'الترتيب', s_featured: 'المميّز', s_low: 'السعر: من الأقل', s_high: 'السعر: من الأعلى',
    items: 'قطعة', add: 'أضف إلى الحقيبة', added: 'أُضيفت', view: 'عرض سريع', close: 'إغلاق', from: 'السعر',
    o_size: 'مقاس الخاتم', o_length: 'طول السلسلة', o_engrave: 'نقش الاسم (اختياري)', o_engrave_ph: 'مثال: محمد', o_gift: 'تغليف هدية (مجاني)', o_qty: 'الكمية', o_cm: 'سم',
    spec_mat: 'الخامة', spec_stone: 'الحجر', spec_warranty: 'الضمان', warranty_watch: 'سنتان', warranty_other: 'سنة على الطلاء واللحام', none: 'بلا حجر',
    at_k: 'الأتيليه', at_ring: 'خاتم', at_watch: 'ساعة', at_beads: 'مسبحة',
    at_pick_ring: 'اختر الحجر', at_pick_watch: 'اختر الميناء', at_pick_beads: 'اختر الحبّات', at_drag: 'اسحب للتدوير', at_see: 'شاهدها في المجموعة',
    d_black: 'أسود', d_navy: 'كحلي', d_white: 'أبيض', d_green: 'أخضر', d_champagne: 'شمبانيا',
    st_k: 'الحرفة', st_t: 'فضة، وحجر، ووقت', st_p: 'نبدأ من الفضة ونُنهي عند التفصيل الصغير الذي تلمسه بإصبعك.',
    p1_t: 'فضة 925', p1_p: 'فضة استرلينغ بدرجة نقاء 92.5%، تُصقل باليد حتى تلمع وتُمَطّ حيث يلزم لتبقى القطعة أنيقة.',
    p2_t: 'أحجار طبيعية', p2_p: 'ياقوت وزمرد وأميثيست وفيروز وعقيق، تُفحص وتُرصَّع بمخالب أو إطار حسب القطعة.',
    p3_t: 'نقش وتخصيص', p3_p: 'تُنقش الأسماء على البلاكات والخواتم بخط عربي أو لاتيني حسب ما تختار.',
    p4_t: 'ساعات تدقّ', p4_p: 'ميناء بإشعاع شمسي وعقرب ثوانٍ يقفز كالساعات الميكانيكية، وسوار من جلد أو من الفضة.',
    or_k: 'الطلب', or_t: 'كيف تطلب؟', or_1: 'اختر القطعة', or_1p: 'أضفها إلى الحقيبة مع المقاس أو النقش', or_2: 'أرسل بواتساب', or_2p: 'تصلنا رسالة جاهزة بطلبك كاملاً', or_3: 'نؤكد ونشحن', or_3p: 'نؤكد التفاصيل والسعر ثم نشحن إليك',
    bag_t: 'حقيبتك', bag_empty: 'الحقيبة فارغة بعد', bag_empty_p: 'أضف قطعة من المجموعة لتبدأ.', bag_sub: 'المجموع', bag_send: 'أرسل الطلب بواتساب', bag_note: 'سيُفتح واتساب برسالة جاهزة بطلبك، ونؤكد معك الأسعار والتفاصيل هناك.', bag_clear: 'إفراغ الحقيبة', rm: 'حذف',
    wa_hi: 'مرحباً، أريد طلب التالي من متجر محمد:', wa_total: 'المجموع', wa_size: 'المقاس', wa_len: 'الطول', wa_eng: 'النقش', wa_gift: 'تغليف هدية', wa_end: 'الاسم والعنوان للتوصيل:',
    cta_t: 'جاهز لتختار؟', cta_p: 'اطلب عبر واتساب، أو اسأل عن قطعة غير موجودة هنا.', cta_btn: 'راسلنا على واتساب',
    foot_demo: 'هذا المتجر نموذج تجريبي: العلامة والمنتجات والأسعار خيالية.', foot_by: 'تصميم وتطوير MOHAMMED Web Studio', foot_top: 'للأعلى',
    err3d: 'تعذّر تشغيل العرض ثلاثي الأبعاد على هذا الجهاز، لكن المتجر يعمل كاملاً.',
    gem_amethyst: 'أميثيست', gem_sapphire: 'ياقوت أزرق', gem_emerald: 'زمرد', gem_ruby: 'ياقوت أحمر', gem_topaz: 'توباز', gem_citrine: 'سيترين', gem_pink: 'توركمالين وردي',
    b_amber: 'كهرمان', b_onyx: 'أونيكس', b_silver: 'فضة', b_tigereye: 'عين النمر', b_turquoise: 'فيروز', b_coral: 'مرجان',
    g_style: "الشكل",
    g_stone: "الحجر",
    g_cut: "قطع الحجر",
    g_size: "حجم الحجر",
    g_thick: "سماكة الفضة",
    g_finish: "التشطيب",
    g_pattern: "نقشة الحلقة",
    g_side: "أحجار جانبية",
    g_glyph: "الحروف على الختم",
    g_inside: "نقش داخل الحلقة (اسم أو تاريخ)",
    l_note: "ملاحظاتك وطلبك الخاص",
    g_dial: "الميناء",
    g_strap: "السوار",
    g_wsize: "قطر العلبة",
    g_case: "تشطيب العلبة",
    g_bezel: "إطار الميناء",
    g_brand: "الاسم على الميناء",
    g_back: "نقش خلف الساعة",
    g_bead: "الحبّات",
    g_count: "عدد الحبّات",
    g_tassel: "الشرّابة",
    g_cap: "نقش على رأس الإمامة",
    rs_solitaire: "سوليتير",
    rs_halo: "هالة",
    rs_trilogy: "ثلاثي",
    rs_bezel: "إطار مغلق",
    rs_cluster: "عنقود",
    rs_eternity: "صف أحجار",
    rs_signet: "ختم",
    rs_band: "حلقة عريضة",
    cut_round: "دائري",
    cut_oval: "بيضاوي",
    cut_emerald: "مستطيل",
    cut_cabochon: "مقوّس أملس",
    sz_s: "صغير · 6 مم",
    sz_m: "وسط · 8 مم",
    sz_l: "كبير · 10 مم",
    th_light: "رقيقة · 1.8 مم",
    th_classic: "كلاسيكية · 2.5 مم",
    th_heavy: "ثقيلة · 3.5 مم",
    fn_polish: "لامع",
    fn_satin: "مطفي ساتان",
    fn_antique: "قديم مؤكسد",
    pt_smooth: "أملس",
    pt_lines: "خطوط",
    pt_chevron: "شيفرون",
    pt_hammer: "مطرقة",
    sd_none: "بدون",
    sd_clear: "صافية",
    sd_match: "بلون الحجر",
    gem_clear: "أبيض صافٍ",
    gem_turquoise: "فيروز",
    gem_agate: "عقيق",
    gem_onyx: "أونيكس",
    gem_coral: "مرجان",
    gem_lapis: "لازورد",
    gem_tigereye: "عين النمر",
    gem_pearl: "لؤلؤ",
    st_silver: "سوار فضة",
    st_black: "جلد أسود",
    st_brown: "جلد بني",
    st_tan: "جلد عسلي",
    st_green: "جلد أخضر",
    st_navy: "جلد كحلي",
    st_burgundy: "جلد عنابي",
    st_grey: "جلد رمادي",
    bz_none: "ناعم",
    bz_clear: "أحجار صافية",
    bz_sapphire: "ياقوت أزرق",
    bz_ruby: "ياقوت أحمر",
    bz_emerald: "زمرد",
    b_pearl: "لؤلؤ",
    b_lapis: "لازورد",
    b_agate: "عقيق",
    b_emerald: "زمرد",
    cnt_33: "33 حبّة",
    cnt_66: "66 حبّة",
    cnt_99: "99 حبّة",
    ts_silver: "فضة",
    ts_black: "أسود",
    ts_burgundy: "عنابي",
    ts_navy: "كحلي",
    ts_ivory: "عاجي",
    ph_glyph: "مثال: م",
    ph_inside: "مثال: اسم أو تاريخ",
    ph_brand: "MOHAMMED",
    ph_back: "مثال: اسم وتاريخ",
    ph_cap: "مثال: اسم",
    ph_note: "اكتب طلبك هنا: حجم أكبر، لون آخر، صورة قطعة أعجبتك...",
    h_glyph: "حتى 3 أحرف لاتينية أو 4 عربية",
    h_brand: "أحرف لاتينية، حتى 10",
    h_note: "إذا لم نجد ما وصفته تماماً، نجد لك أقرب شيء إلى طلبك.",
    at_sum: "تصميمك",
    at_price: "السعر التقديري",
    at_price_note: "تقدير فقط، والسعر النهائي نؤكده معك على واتساب.",
    at_add: "أضف التصميم إلى الحقيبة",
    at_wa: "أرسل التصميم على واتساب",
    at_save: "احفظ صورة التصميم",
    at_steps: "بعد الانتهاء من تصميم قطعتك:",
    at_step1: "احفظ صورة التصميم.",
    at_step2: "أرسل لنا التفاصيل على واتساب وأرفق الصورة في المحادثة.",
    at_saved: "حُفظت الصورة. أرفقها في محادثة واتساب.",
    at_added: "أُضيف التصميم إلى الحقيبة",
    c_ring: "خاتم بتصميمك",
    c_watch: "ساعة بتصميمك",
    c_beads: "مسبحة بتصميمك",
    wa_design: "مرحباً، صمّمت هذه القطعة على موقعكم وأريد طلبها:",
    wa_pic: "سأرفق صورة التصميم في المحادثة.",
    wa_est: "السعر التقديري",
    theme: "اللون",
    thm_obsidian: "أسود شمبانيا",
    thm_emerald: "أخضر عميق",
    thm_burgundy: "عنابي",
    at_t: "صمّم قطعتك بنفسك",
    at_p: "اختر الشكل والحجر وسماكة الفضة والنقش وكل التفاصيل، ثم نصنعها لك أو نجد أقرب شيء إلى طلبك."
  },
  en: {
    title: 'MOHAMMED · Watches & Silver with Gemstones',
    brandSub: 'Watches · Silver · Gemstones',
    nav_collection: 'Collection', nav_atelier: 'Atelier', nav_story: 'Craft', nav_order: 'Order',
    sound_on: 'Sound on', sound_off: 'Sound off', bag: 'Bag', bag_open: 'Open bag', lang: 'Language',
    loader: 'Preparing the showroom',
    scroll: 'Scroll',
    c0_k: 'Watches · Silver · Gemstones', c0_t: 'Time, set in silver', c0_p: 'Watches and silver pieces set with gemstones, with details you only notice up close. This one is ticking in your own time.',
    c1_k: 'Anatomy of a watch', c1_t: 'Beneath the dial', c1_p: 'Crystal, dial, movement, case. Four layers working as one, with three ruby jewels at the heart.',
    a_crystal: 'Crystal', a_dial: 'Dial', a_movement: 'Movement', a_case: 'Silver case',
    c2_k: 'Silver with gemstones', c2_t: 'One stone changes the piece', c2_p: 'Ruby, emerald, turquoise, agate. Each stone is chosen and set in 925 silver.',
    c3_k: 'Prayer beads & name plates', c3_t: 'Beads, and a plate with your name', c3_p: '33 beads of amber, onyx or silver, and a name plate engraved with whoever you choose.',
    c4_k: 'The collection', c4_t: 'All of it, in one place', c4_p: 'Six watches, seven rings, name plates, chains and torcs, and prayer beads. Choose what feels like you.', c4_cta: 'Browse the collection',
    trust1_t: '925 silver', trust1_p: 'Pure sterling silver',
    trust2_t: 'Name engraving', trust2_p: 'On plates and rings',
    trust3_t: 'Gift packaging', trust3_p: 'A velvet box with every order',
    trust4_t: 'Order on WhatsApp', trust4_p: 'A bag that sends to us',
    col_k: 'Collection', col_t: 'Choose your piece', col_p: 'Watches, rings, name plates, chains and torcs, and prayer beads, all priced in Turkish lira.',
    f_all: 'All', f_watch: 'Watches', f_ring: 'Rings', f_pendant: 'Name plates', f_necklace: 'Chains & torcs', f_tasbih: 'Prayer beads',
    sort: 'Sort', s_featured: 'Featured', s_low: 'Price: low to high', s_high: 'Price: high to low',
    items: 'pieces', add: 'Add to bag', added: 'Added', view: 'Quick view', close: 'Close', from: 'Price',
    o_size: 'Ring size', o_length: 'Chain length', o_engrave: 'Name engraving (optional)', o_engrave_ph: 'e.g. Mohammed', o_gift: 'Gift packaging (free)', o_qty: 'Quantity', o_cm: 'cm',
    spec_mat: 'Material', spec_stone: 'Stone', spec_warranty: 'Warranty', warranty_watch: '2 years', warranty_other: '1 year on plating and soldering', none: 'No stone',
    at_k: 'The Atelier', at_ring: 'Ring', at_watch: 'Watch', at_beads: 'Prayer beads',
    at_pick_ring: 'Choose the stone', at_pick_watch: 'Choose the dial', at_pick_beads: 'Choose the beads', at_drag: 'Drag to rotate', at_see: 'See it in the collection',
    d_black: 'Black', d_navy: 'Navy', d_white: 'White', d_green: 'Green', d_champagne: 'Champagne',
    st_k: 'The craft', st_t: 'Silver, stone and time', st_p: 'We start with the silver and finish at the small detail you feel under your finger.',
    p1_t: '925 silver', p1_p: 'Sterling silver at 92.5% purity, hand polished until it glows and finished where it matters most.',
    p2_t: 'Natural stones', p2_p: 'Ruby, emerald, amethyst, turquoise and agate, inspected and set with claws or a bezel depending on the piece.',
    p3_t: 'Engraving & custom', p3_p: 'Names are engraved on plates and rings in Arabic or Latin letters, as you choose.',
    p4_t: 'Watches that tick', p4_p: 'A sunburst dial and a second hand that jumps like a mechanical watch, on leather or a silver bracelet.',
    or_k: 'Ordering', or_t: 'How to order', or_1: 'Pick a piece', or_1p: 'Add it to the bag with your size or engraving', or_2: 'Send on WhatsApp', or_2p: 'A ready message with your full order reaches us', or_3: 'We confirm and ship', or_3p: 'We confirm details and price, then ship to you',
    bag_t: 'Your bag', bag_empty: 'Your bag is empty', bag_empty_p: 'Add a piece from the collection to begin.', bag_sub: 'Total', bag_send: 'Send order on WhatsApp', bag_note: 'WhatsApp opens with a ready message of your order, and we confirm prices and details there.', bag_clear: 'Empty bag', rm: 'Remove',
    wa_hi: 'Hello, I would like to order the following from MOHAMMED:', wa_total: 'Total', wa_size: 'Size', wa_len: 'Length', wa_eng: 'Engraving', wa_gift: 'Gift packaging', wa_end: 'Name and delivery address:',
    cta_t: 'Ready to choose?', cta_p: 'Order on WhatsApp, or ask about a piece that is not listed here.', cta_btn: 'Message us on WhatsApp',
    foot_demo: 'This store is a concept demo: the brand, products and prices are fictional.', foot_by: 'Designed & built by MOHAMMED Web Studio', foot_top: 'Back to top',
    err3d: '3D view could not start on this device, but the store works fully.',
    gem_amethyst: 'Amethyst', gem_sapphire: 'Sapphire', gem_emerald: 'Emerald', gem_ruby: 'Ruby', gem_topaz: 'Topaz', gem_citrine: 'Citrine', gem_pink: 'Pink tourmaline',
    b_amber: 'Amber', b_onyx: 'Onyx', b_silver: 'Silver', b_tigereye: "Tiger's eye", b_turquoise: 'Turquoise', b_coral: 'Coral',
    g_style: "Ring style",
    g_stone: "Stone",
    g_cut: "Stone cut",
    g_size: "Stone size",
    g_thick: "Silver thickness",
    g_finish: "Finish",
    g_pattern: "Band pattern",
    g_side: "Side stones",
    g_glyph: "Letters on the signet",
    g_inside: "Inside engraving (name or date)",
    l_note: "Your notes and special requests",
    g_dial: "Dial",
    g_strap: "Strap",
    g_wsize: "Case size",
    g_case: "Case finish",
    g_bezel: "Bezel",
    g_brand: "Name on the dial",
    g_back: "Caseback engraving",
    g_bead: "Beads",
    g_count: "Number of beads",
    g_tassel: "Tassel",
    g_cap: "Engraving on the cap",
    rs_solitaire: "Solitaire",
    rs_halo: "Halo",
    rs_trilogy: "Trilogy",
    rs_bezel: "Bezel set",
    rs_cluster: "Cluster",
    rs_eternity: "Eternity",
    rs_signet: "Signet",
    rs_band: "Wide band",
    cut_round: "Round",
    cut_oval: "Oval",
    cut_emerald: "Emerald cut",
    cut_cabochon: "Cabochon",
    sz_s: "Small · 6 mm",
    sz_m: "Medium · 8 mm",
    sz_l: "Large · 10 mm",
    th_light: "Light · 1.8 mm",
    th_classic: "Classic · 2.5 mm",
    th_heavy: "Heavy · 3.5 mm",
    fn_polish: "Polished",
    fn_satin: "Satin matte",
    fn_antique: "Antique oxidized",
    pt_smooth: "Smooth",
    pt_lines: "Lines",
    pt_chevron: "Chevron",
    pt_hammer: "Hammered",
    sd_none: "None",
    sd_clear: "Clear stones",
    sd_match: "Matching",
    gem_clear: "Clear white",
    gem_turquoise: "Turquoise",
    gem_agate: "Agate (Aqeeq)",
    gem_onyx: "Onyx",
    gem_coral: "Coral",
    gem_lapis: "Lapis lazuli",
    gem_tigereye: "Tiger's eye",
    gem_pearl: "Pearl",
    st_silver: "Silver bracelet",
    st_black: "Black leather",
    st_brown: "Brown leather",
    st_tan: "Tan leather",
    st_green: "Green leather",
    st_navy: "Navy leather",
    st_burgundy: "Burgundy leather",
    st_grey: "Grey leather",
    bz_none: "Plain",
    bz_clear: "Clear stones",
    bz_sapphire: "Sapphires",
    bz_ruby: "Rubies",
    bz_emerald: "Emeralds",
    b_pearl: "Pearl",
    b_lapis: "Lapis",
    b_agate: "Agate",
    b_emerald: "Emerald",
    cnt_33: "33 beads",
    cnt_66: "66 beads",
    cnt_99: "99 beads",
    ts_silver: "Silver",
    ts_black: "Black",
    ts_burgundy: "Burgundy",
    ts_navy: "Navy",
    ts_ivory: "Ivory",
    ph_glyph: "e.g. M",
    ph_inside: "e.g. a name or date",
    ph_brand: "MOHAMMED",
    ph_back: "e.g. a name and date",
    ph_cap: "e.g. a name",
    ph_note: "Write your request here: a bigger stone, another colour, a photo of a piece you like...",
    h_glyph: "Up to 3 Latin or 4 Arabic letters",
    h_brand: "Latin letters, up to 10",
    h_note: "If we don't have exactly what you describe, we'll find the closest thing to your request.",
    at_sum: "Your design",
    at_price: "Estimated price",
    at_price_note: "An estimate only; we confirm the final price with you on WhatsApp.",
    at_add: "Add this design to the bag",
    at_wa: "Send the design on WhatsApp",
    at_save: "Save a picture of the design",
    at_steps: "When you finish designing your piece:",
    at_step1: "Save the picture of your design.",
    at_step2: "Send us the details on WhatsApp and attach the picture in the chat.",
    at_saved: "Picture saved. Attach it in the WhatsApp chat.",
    at_added: "Design added to the bag",
    c_ring: "Custom ring",
    c_watch: "Custom watch",
    c_beads: "Custom prayer beads",
    wa_design: "Hello, I designed this piece on your site and would like to order it:",
    wa_pic: "I will attach a picture of the design in this chat.",
    wa_est: "Estimated price",
    theme: "Colour",
    thm_obsidian: "Obsidian",
    thm_emerald: "Deep green",
    thm_burgundy: "Burgundy",
    at_t: "Design your own piece",
    at_p: "Pick the shape, stone, silver thickness, engraving and every detail. We make it for you, or find the closest thing to your request."
  },
  tr: {
    title: 'MOHAMMED · Değerli Taşlı Gümüş ve Saat',
    brandSub: 'Saat · Gümüş · Değerli Taş',
    nav_collection: 'Koleksiyon', nav_atelier: 'Atölye', nav_story: 'Zanaat', nav_order: 'Sipariş',
    sound_on: 'Sesi aç', sound_off: 'Sesi kapat', bag: 'Sepet', bag_open: 'Sepeti aç', lang: 'Dil',
    loader: 'Mağaza hazırlanıyor',
    scroll: 'Kaydır',
    c0_k: 'Saat · Gümüş · Değerli Taş', c0_t: 'Zaman, gümüşle yazılır', c0_p: 'Değerli taşlarla süslü saat ve gümüş takılar, ancak yakından fark edilen detaylarla. Bu saat şu an sizin saatinizle çalışıyor.',
    c1_k: 'Bir saatin anatomisi', c1_t: 'Kadranın altında', c1_p: 'Cam, kadran, mekanizma, kasa. Birlikte çalışan dört katman ve kalpte üç yakut taş.',
    a_crystal: 'Cam', a_dial: 'Kadran', a_movement: 'Mekanizma', a_case: 'Gümüş kasa',
    c2_k: 'Değerli taşlı gümüş', c2_t: 'Tek bir taş her şeyi değiştirir', c2_p: 'Yakut, zümrüt, firuze, akik. Her taş seçilir ve 925 ayar gümüşe işlenir.',
    c3_k: 'Tesbih ve isim plakaları', c3_t: 'Tesbih, bir de adınızla plaka', c3_p: 'Kehribar, oniks veya gümüşten 33 tane ve sevdiğiniz isimle kazınan bir plaka.',
    c4_k: 'Koleksiyon', c4_t: 'Hepsi tek yerde', c4_p: 'Altı saat, yedi yüzük, isim plakaları, zincir ve tasmalar, tesbihler. Size benzeyeni seçin.', c4_cta: 'Koleksiyonu gez',
    trust1_t: '925 ayar gümüş', trust1_p: 'Saf sterling gümüş',
    trust2_t: 'İsim kazıma', trust2_p: 'Plaka ve yüzüklerde',
    trust3_t: 'Hediye paketi', trust3_p: 'Her siparişle kadife kutu',
    trust4_t: 'WhatsApp ile sipariş', trust4_p: 'Doğrudan bize giden sepet',
    col_k: 'Koleksiyon', col_t: 'Parçanızı seçin', col_p: 'Saat, yüzük, isim plakası, zincir ve tasma, tesbih. Fiyatlar Türk lirası ile.',
    f_all: 'Tümü', f_watch: 'Saatler', f_ring: 'Yüzükler', f_pendant: 'İsim plakaları', f_necklace: 'Zincir ve tasma', f_tasbih: 'Tesbihler',
    sort: 'Sırala', s_featured: 'Öne çıkan', s_low: 'Fiyat: düşükten yükseğe', s_high: 'Fiyat: yüksekten düşüğe',
    items: 'ürün', add: 'Sepete ekle', added: 'Eklendi', view: 'Hızlı bakış', close: 'Kapat', from: 'Fiyat',
    o_size: 'Yüzük ölçüsü', o_length: 'Zincir uzunluğu', o_engrave: 'İsim kazıma (isteğe bağlı)', o_engrave_ph: 'Örn. Mohammed', o_gift: 'Hediye paketi (ücretsiz)', o_qty: 'Adet', o_cm: 'cm',
    spec_mat: 'Malzeme', spec_stone: 'Taş', spec_warranty: 'Garanti', warranty_watch: '2 yıl', warranty_other: 'Kaplama ve lehimde 1 yıl', none: 'Taşsız',
    at_k: 'Atölye', at_ring: 'Yüzük', at_watch: 'Saat', at_beads: 'Tesbih',
    at_pick_ring: 'Taşı seçin', at_pick_watch: 'Kadranı seçin', at_pick_beads: 'Taneleri seçin', at_drag: 'Çevirmek için sürükle', at_see: 'Koleksiyonda gör',
    d_black: 'Siyah', d_navy: 'Lacivert', d_white: 'Beyaz', d_green: 'Yeşil', d_champagne: 'Şampanya',
    st_k: 'Zanaat', st_t: 'Gümüş, taş ve zaman', st_p: 'Gümüşle başlarız, parmağınızın altında hissettiğiniz küçük detayla bitiririz.',
    p1_t: '925 ayar gümüş', p1_p: '%92,5 saflıkta sterling gümüş, parlayana kadar elde cilalanır ve gereken yerde mat bırakılır.',
    p2_t: 'Doğal taşlar', p2_p: 'Yakut, zümrüt, ametist, firuze ve akik; kontrol edilir, parçaya göre tırnak veya çerçeve ile işlenir.',
    p3_t: 'Kazıma ve kişiye özel', p3_p: 'İsimler plaka ve yüzüklere Arapça veya Latin harflerle, seçtiğiniz gibi kazınır.',
    p4_t: 'Tık tık işleyen saatler', p4_p: 'Güneş ışını desenli kadran ve mekanik saat gibi atlayan saniye ibresi; deri veya gümüş bilezikle.',
    or_k: 'Sipariş', or_t: 'Nasıl sipariş verilir?', or_1: 'Parçayı seçin', or_1p: 'Ölçü veya kazımayla sepete ekleyin', or_2: 'WhatsApp ile gönderin', or_2p: 'Siparişinizin hazır mesajı bize ulaşır', or_3: 'Onaylar, göndeririz', or_3p: 'Detay ve fiyatı onaylar, size göndeririz',
    bag_t: 'Sepetiniz', bag_empty: 'Sepetiniz boş', bag_empty_p: 'Başlamak için koleksiyondan bir parça ekleyin.', bag_sub: 'Toplam', bag_send: 'Siparişi WhatsApp ile gönder', bag_note: 'WhatsApp, siparişinizin hazır mesajıyla açılır; fiyat ve detayları orada onaylarız.', bag_clear: 'Sepeti boşalt', rm: 'Sil',
    wa_hi: 'Merhaba, MOHAMMED mağazasından şunları sipariş etmek istiyorum:', wa_total: 'Toplam', wa_size: 'Ölçü', wa_len: 'Uzunluk', wa_eng: 'Kazıma', wa_gift: 'Hediye paketi', wa_end: 'Ad ve teslimat adresi:',
    cta_t: 'Seçmeye hazır mısınız?', cta_p: 'WhatsApp ile sipariş verin veya burada olmayan bir parçayı sorun.', cta_btn: "WhatsApp'tan yazın",
    foot_demo: 'Bu mağaza bir konsept demodur: marka, ürünler ve fiyatlar kurgudur.', foot_by: 'MOHAMMED Web Studio tarafından tasarlandı', foot_top: 'Yukarı',
    err3d: '3B görünüm bu cihazda başlatılamadı, ancak mağaza tam çalışıyor.',
    gem_amethyst: 'Ametist', gem_sapphire: 'Safir', gem_emerald: 'Zümrüt', gem_ruby: 'Yakut', gem_topaz: 'Topaz', gem_citrine: 'Sitrin', gem_pink: 'Pembe turmalin',
    b_amber: 'Kehribar', b_onyx: 'Oniks', b_silver: 'Gümüş', b_tigereye: 'Kaplan gözü', b_turquoise: 'Firuze', b_coral: 'Mercan',
    g_style: "Yüzük modeli",
    g_stone: "Taş",
    g_cut: "Taş kesimi",
    g_size: "Taş boyutu",
    g_thick: "Gümüş kalınlığı",
    g_finish: "Yüzey",
    g_pattern: "Halka deseni",
    g_side: "Yan taşlar",
    g_glyph: "Mühürdeki harfler",
    g_inside: "İç kazıma (isim veya tarih)",
    l_note: "Notlarınız ve özel istekleriniz",
    g_dial: "Kadran",
    g_strap: "Kordon",
    g_wsize: "Kasa boyutu",
    g_case: "Kasa yüzeyi",
    g_bezel: "Çerçeve",
    g_brand: "Kadrandaki isim",
    g_back: "Kasa arkası kazıma",
    g_bead: "Taneler",
    g_count: "Tane sayısı",
    g_tassel: "Püskül",
    g_cap: "Başlık kazıma",
    rs_solitaire: "Tek taş",
    rs_halo: "Halo",
    rs_trilogy: "Üçlü",
    rs_bezel: "Çerçeve ayar",
    rs_cluster: "Çiçek",
    rs_eternity: "Sıralı taş",
    rs_signet: "Mühür",
    rs_band: "Geniş alyans",
    cut_round: "Yuvarlak",
    cut_oval: "Oval",
    cut_emerald: "Baget",
    cut_cabochon: "Kabaşon",
    sz_s: "Küçük · 6 mm",
    sz_m: "Orta · 8 mm",
    sz_l: "Büyük · 10 mm",
    th_light: "İnce · 1,8 mm",
    th_classic: "Klasik · 2,5 mm",
    th_heavy: "Kalın · 3,5 mm",
    fn_polish: "Parlak",
    fn_satin: "Saten mat",
    fn_antique: "Antik oksit",
    pt_smooth: "Düz",
    pt_lines: "Çizgili",
    pt_chevron: "Şevron",
    pt_hammer: "Çekiç dokulu",
    sd_none: "Yok",
    sd_clear: "Şeffaf taşlar",
    sd_match: "Aynı renk",
    gem_clear: "Beyaz şeffaf",
    gem_turquoise: "Firuze",
    gem_agate: "Akik",
    gem_onyx: "Oniks",
    gem_coral: "Mercan",
    gem_lapis: "Lapis",
    gem_tigereye: "Kaplan gözü",
    gem_pearl: "İnci",
    st_silver: "Gümüş bilezik",
    st_black: "Siyah deri",
    st_brown: "Kahverengi deri",
    st_tan: "Taba deri",
    st_green: "Yeşil deri",
    st_navy: "Lacivert deri",
    st_burgundy: "Bordo deri",
    st_grey: "Gri deri",
    bz_none: "Düz",
    bz_clear: "Şeffaf taşlar",
    bz_sapphire: "Safirler",
    bz_ruby: "Yakutlar",
    bz_emerald: "Zümrütler",
    b_pearl: "İnci",
    b_lapis: "Lapis",
    b_agate: "Akik",
    b_emerald: "Zümrüt",
    cnt_33: "33 tane",
    cnt_66: "66 tane",
    cnt_99: "99 tane",
    ts_silver: "Gümüş",
    ts_black: "Siyah",
    ts_burgundy: "Bordo",
    ts_navy: "Lacivert",
    ts_ivory: "Fildişi",
    ph_glyph: "örn. M",
    ph_inside: "örn. isim veya tarih",
    ph_brand: "MOHAMMED",
    ph_back: "örn. isim ve tarih",
    ph_cap: "örn. isim",
    ph_note: "İsteğinizi yazın: daha büyük taş, başka renk, beğendiğiniz bir parçanın fotoğrafı...",
    h_glyph: "3 Latin veya 4 Arap harfi",
    h_brand: "Latin harfler, en fazla 10",
    h_note: "Tarif ettiğinizin aynısı yoksa, isteğinize en yakın olanı buluruz.",
    at_sum: "Tasarımınız",
    at_price: "Tahmini fiyat",
    at_price_note: "Yalnızca tahmindir; nihai fiyatı WhatsApp'ta onaylarız.",
    at_add: "Tasarımı sepete ekle",
    at_wa: "Tasarımı WhatsApp'tan gönder",
    at_save: "Tasarımın resmini kaydet",
    at_steps: "Parçanızı tasarlamayı bitirince:",
    at_step1: "Tasarımın resmini kaydedin.",
    at_step2: "Ayrıntıları WhatsApp'tan gönderin, resmi sohbete ekleyin.",
    at_saved: "Resim kaydedildi. WhatsApp sohbetine ekleyin.",
    at_added: "Tasarım sepete eklendi",
    c_ring: "Özel tasarım yüzük",
    c_watch: "Özel tasarım saat",
    c_beads: "Özel tasarım tesbih",
    wa_design: "Merhaba, bu parçayı sitenizde tasarladım ve sipariş etmek istiyorum:",
    wa_pic: "Tasarımın resmini bu sohbete ekleyeceğim.",
    wa_est: "Tahmini fiyat",
    theme: "Renk",
    thm_obsidian: "Obsidyen",
    thm_emerald: "Zümrüt yeşili",
    thm_burgundy: "Bordo",
    at_t: "Kendi parçanı tasarla",
    at_p: "Modeli, taşı, gümüş kalınlığını, kazımayı ve her ayrıntıyı seç; biz yapalım ya da isteğine en yakın olanı bulalım."
  }
};
